apiVersion: v1
kind: Service
metadata:
  name: todoapp-nodeport
  namespace: {{ .Values.todoapp.namespace }}
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    {{- if .Values.todoapp.nodePort }}
    nodePort: {{ .Values.todoapp.nodePort }}
    {{- end }}